config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :subcategories
  end


  root 'categories#index'

  match '/help',    to: 'pages#help',     via: :get
  match '/scams',   to: 'pages#scams',    via: :get
  match '/tips',    to: 'pages#tips',     via: :get
  match '/terms',   to: 'pages#terms',    via: :get 
  match '/privacy', to: 'pages#privacy',  via: :get
  match '/about',   to: 'pages#about',    via: :get
  match '/contact', to: 'pages#contact',  via: :get

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :subcategories
	has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :category
	belongs_to :subcategory
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
		
		@dining = @categories[2]
		@entertainment = @categories[3]
		@retail = @categories[4]
		@activity = @categories[5]
		@travel = @categories[6]
		@misc = @categories[7]
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def help
	end

	def scams
	end

	def tips
	end

	def terms
	end

	def privacy
	end

	def about
	end

	def contact
	end

end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="container">
  <div class="leftbar">
    <a href="#"><h1>Vouchr</h1></a>
    <ul>
      <a href="#">post to classifieds</a>
      <li>my account</li>
    </ul>
    <form>
      <p>search rubyslist</p>
      <input type="text" name="firstname" placeholder="search" size="20">
      <br>
      <input type="text" name="firstname" placeholder="where" size="20">
      <br>
      <select>
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option>
      </select>
      <button type="button">>
      </button>
    </form>
  </div>
  <div class="center-column" >
    <div class="center-one">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'dining' %></th>
        </tr>
        <tr>
          <td>
            <% @dining.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'entertainment' %></th>
        </tr>
        <tr>
          <td>
             <% @entertainment.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'retail' %></th>
        </tr>
        <tr>
          <td>
             <% @retail.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="center-two">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'activity' %></th>
        </tr>
        <tr>
          <td>
            <% @activity.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name %></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'travel' %></th>
        </tr>
        <tr>
          <td>
            <% @travel.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name %></li>
            </ul>
            <% end %>
            </ul>
          </td>
        </tr>
      </table>
    </div>
    <div class="center-three">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'misc' %></th>
        </tr>
        <tr>
          <td>
            <% @misc.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name %></li>
            </ul>
            <% end %>
            </ul>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="rightbar">
    <ul class="rightbar-top">
      <li><%= link_to 'help and faq', help_path %></li>
      <li><%= link_to 'avoid scams and fraud', scams_path %></li>
      <li><%= link_to 'personal safety tips', tips_path %></li>
      <li class="rightbar-top"><%= link_to 'terms of use', terms_path %></li>
      <li><%= link_to 'privacy policy', privacy_path %></li>
       <li><%= link_to 'about Vouchr ', about_path %></li>
       <li><%= link_to 'contact us', contact_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vouchr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/contact.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/help.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/privacy.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/scams.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/terms.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>

app/views/pages/tips.html.erb
<div class="topbar">
  <div class="container">
    rubyslist
  </div>
</div>
<div class="container">
    <p>iLorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Vestibulum varius mi vel ipsum ultrices, non volutpat nisl viverra. 
    Sed rhoncus elementum tortor, vitae condimentum dolor. Vestibulum 
    imperdiet velit ac fringilla pulvinar. Nunc euismod justo sit amet 
    turpis tincidunt, id ultricies neque scelerisque. Sed ullamcorper id 
    risus gravida pulvinar. Fusce iaculis elit orci, eget mattis quam dapibus 
    id. Pellentesque iaculis et neque sed bibendum. Nullam hendrerit, orci 
    laoreet sodales molestie, enim lectus posuere ligula, id ultrices eros nisl 
    nec purus. Aliquam sit amet porttitor leo, in iaculis felis.

    Duis enim est, luctus at nibh in, consequat sollicitudin purus. Curabitur 
    posuere vulputate massa cursus interdum. Nam a imperdiet quam. Morbi 
    lacinia, eros eget facilisis porta, ante elit rhoncus nisi, id tristique 
    augue nibh vitae ligula. Suspendisse tincidunt non est vitae rhoncus. Nulla 
    tincidunt tempor turpis sed rutrum. Aliquam pharetra malesuada dui, ut 
    porttitor risus luctus at. Proin aliquam pretium accumsan.

    In at elit eu purus tincidunt finibus. Morbi vestibulum lacus et nunc
    accumsan tempor. Curabitur egestas vitae nulla sit amet pellentesque. Etiam 
    ullamcorper efficitur felis, vel pellentesque sapien sagittis at. Lorem 
    ipsum dolor sit amet, consectetur adipiscing elit. Proin ante dui, varius a 
    metus quis, egestas pellentesque leo. Aliquam pellentesque rhoncus metus 
    vitae molestie. Morbi lorem urna, cursus in maximus sit amet, maximus nec 
    diam. Praesent quis facilisis mauris.
    </p>
</div>